name: Fetch Montréal parks — weekly

on:
  schedule:
    - cron: "10 4 * * 3"    #mercredi 04:10 UTC ≈ 00:10 heure de Montréal l’été

jobs:
  fetch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PiqueMe/backend/park-fetcher   # Acces au dossier du script

    steps:
      # 1) Récupère le code
      - uses: actions/checkout@v4

      # 2) Installe Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) Installe les dépendances
      - run: npm ci

      # 4) Injecte la clé de service de Firebase
      - name: Write serviceAccountKey.json
        run: |
          echo "${{ secrets.FIREBASE_SA_KEY_B64 }}" | base64 -d > serviceAccountKey.json

      # 5) Exécute ton script
      - run: node fetchParks.js
