name: Fetch Montréal parks — weekly

on:
  schedule:
    # Tous les lundis à 02 h 15 UTC  (dimanche 22 h 15 à Montréal l'été)
    - cron: "15 2 * * 1"
  workflow_dispatch:        # permet de déclencher manuellement si besoin

jobs:
  fetch:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: PiqueMe/backend/park-fetcher   # Acces au dossier du script

    steps:
      # 1) Récupère le code
      - uses: actions/checkout@v4

      # 2) Installe Node
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      # 3) Installe les dépendances
      - run: npm ci

      # 4) Injecte la clé de service de Firebase
      - name: Write serviceAccountKey.json
        run: |
          echo "${{ secrets.FIREBASE_SA_KEY_B64 }}" | base64 -d > serviceAccountKey.json

      # 5) Exécute ton script
      - run: node fetchParks.js
